spring.application.name=admin-backend

# Server Configuration
server.port=28080

# Database Configuration (MongoDB)
spring.data.mongodb.uri=mongodb+srv://food_admin:Food123@cluster0.m2waosw.mongodb.net/foodiebuddy?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.auto-index-creation=true

# JPA (not needed for MongoDB, but harmless if another module uses it)
spring.jpa.hibernate.ddl-auto=upda
# Lazy initialization for MongoDB
spring.data.mongodb.lazy-initialization=true

# JWT Configuration
# Generates via: openssl rand -base64 64
jwt.secret=9B948332E90124FD6F8BA06733224B27AE2DFFDAAD6A0D523C641DC5E21B90FE5ECC4ECBC7D01FA9706C8B4C02506EA9C394A790F3BFF61266B3EB6AAAEBA1BE
jwt.expiration=86400000

# OpenAPI/Swagger Config
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
